Smalltalk at: #Horde3DConstants put: (PoolConstantsDictionary named: #Horde3DConstants).

"Scene root node"
Horde3DConstants at: 'RootNode' put: 1.

"Resource types"
Horde3DConstants at: 'Undefined' put: 0.
Horde3DConstants at: 'SceneGraph' put: 1.
Horde3DConstants at: 'Geometry' put: 2.
Horde3DConstants at: 'Animation' put: 3.
Horde3DConstants at: 'Material' put: 4.
Horde3DConstants at: 'Code' put: 5.
Horde3DConstants at: 'Shader' put: 6.
Horde3DConstants at: 'Texture2D' put: 7.
Horde3DConstants at: 'TextureCube' put: 8.
Horde3DConstants at: 'Effect' put: 9.
Horde3DConstants at: 'Pipeline' put: 10.
Horde3DConstants at: 'FontMaterial' put: 11.

"Scene node types"
Horde3DConstants at: 'Group' put: 1.
Horde3DConstants at: 'Model' put: 2.
Horde3DConstants at: 'Mesh' put: 3.
Horde3DConstants at: 'Joint' put: 4.
Horde3DConstants at: 'Light' put: 5.
Horde3DConstants at: 'Camera' put: 6.
Horde3DConstants at: 'Emitter' put: 7.

"Light node parameters constants"
Horde3DConstants at: 'MaterialRes' put: 500.
Horde3DConstants at: 'Radius' put: 501.
Horde3DConstants at: 'FOV' put: 502.
Horde3DConstants at: 'Col_R' put: 503.
Horde3DConstants at: 'Col_G' put: 504.
Horde3DConstants at: 'Col_B' put: 505.
Horde3DConstants at: 'ShadowMapCount' put: 506.
Horde3DConstants at: 'ShadowSplitLambda' put: 507.
Horde3DConstants at: 'ShadowMapBias' put: 508.

"Camera node parameters constants"
Horde3DConstants at: 'PipelineRes' put: 600.
Horde3DConstants at: 'OutputTex' put: 601.
Horde3DConstants at: 'OutputBufferIndex' put: 602.
Horde3DConstants at: 'LeftPlane' put: 603.
Horde3DConstants at: 'RightPlane' put: 604.
Horde3DConstants at: 'BottomPlane' put: 605.
Horde3DConstants at: 'TopPlane' put: 606.
Horde3DConstants at: 'NearPlane' put: 607.
Horde3DConstants at: 'FarPlane' put: 608.
Horde3DConstants at: 'Orthographic' put: 609.
Horde3DConstants at: 'OcclusionCulling' put: 610.

"Engine option parameters constants"
Horde3DConstants at: 'MaxLogLevel' put: 1.
Horde3DConstants at: 'TrilinearFiltering' put: 2.
Horde3DConstants at: 'AnisotropyFactor' put: 3.
Horde3DConstants at: 'TexCompression' put: 4.
Horde3DConstants at: 'LoadTextures' put: 5.
Horde3DConstants at: 'FastAnimation' put: 6.
Horde3DConstants at: 'ShadowMapSize' put: 7.
Horde3DConstants at: 'SampleCount' put: 8.
Horde3DConstants at: 'WireframeMode' put: 9.
Horde3DConstants at: 'DebugViewMode' put: 10.
